db:
  image: kartoza/postgis:9.4-2.1
  container_name: gfdrr_oondra-db
  hostname: geonode-db
  volumes:
    - ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker
  ports:
    - "6113:5432"

geonode:
  build: docker-geonode
  container_name: gfdrr_oondra-geonode
  hostname: geonode
  volumes:
    - ./logs:/var/log/
    - ./geoserver_data:/geonode/geoserver/data
  ports:
    - "8111:8000"
    - "8181:8080"
  links:
    - db:db
  external_links:
    - dockerosm_db:dockerosm_db
  environment:
    - DATABASE_NAME=gis
    - DATABASE_USERNAME=docker
    - DATABASE_PASSWORD=docker
    - DATABASE_HOST=db
    # osm-db links
    - USER=docker
    - PASSWORD=docker
    - PORT=5432
    - HOST=dockerosm_db  
    - DATABASE=gis